import type { NarrativeListItem, ProviderInfo } from '@narrative-launcher/shared-types';

export const MOCK_NARRATIVES: NarrativeListItem[] = [
  {
    id: 'n-001',
    ticker: 'WARCAT',
    name: 'War Cat',
    imageUrl: null,
    narrativeScore: 92,
    status: 'active',
    xPost: {
      tweetId: '1234567890',
      authorUsername: 'cryptodegen',
      text: 'this meme deserves a coin $WARCAT 🐱',
      likeCount: 12400,
      repostCount: 3420,
      viewCount: 480000,
      canonicalUrl: 'https://x.com/cryptodegen/status/1234567890',
    },
    launchCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'n-002',
    ticker: 'AIDOG',
    name: 'AI Dog',
    imageUrl: null,
    narrativeScore: 87,
    status: 'active',
    xPost: {
      tweetId: '1234567891',
      authorUsername: 'solanamaxi',
      text: 'someone should launch $AIDOG immediately',
      likeCount: 8900,
      repostCount: 2100,
      viewCount: 320000,
      canonicalUrl: 'https://x.com/solanamaxi/status/1234567891',
    },
    launchCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'n-003',
    ticker: 'BUILD',
    name: 'Build',
    imageUrl: null,
    narrativeScore: 78,
    status: 'launched',
    xPost: {
      tweetId: '1234567892',
      authorUsername: 'shibainu_dev',
      text: 'launch $BUILD we need a coin for builders not degens',
      likeCount: 5600,
      repostCount: 1800,
      viewCount: 210000,
      canonicalUrl: 'https://x.com/shibainu_dev/status/1234567892',
    },
    launchCount: 1,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'n-004',
    ticker: 'PEPALEO',
    name: 'Pepe Aleo',
    imageUrl: null,
    narrativeScore: 71,
    status: 'active',
    xPost: {
      tweetId: '1234567893',
      authorUsername: 'memecoinqueen',
      text: 'where is $PEPALEO? this narrative is cooking',
      likeCount: 4200,
      repostCount: 890,
      viewCount: 145000,
      canonicalUrl: 'https://x.com/memecoinqueen/status/1234567893',
    },
    launchCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'n-005',
    ticker: 'MOONPIG',
    name: 'Moon Pig',
    imageUrl: null,
    narrativeScore: 65,
    status: 'active',
    xPost: {
      tweetId: '1234567894',
      authorUsername: 'soltrader99',
      text: 'coin this $MOONPIG gm',
      likeCount: 3100,
      repostCount: 670,
      viewCount: 98000,
      canonicalUrl: 'https://x.com/soltrader99/status/1234567894',
    },
    launchCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'n-006',
    ticker: 'VIBECAT',
    name: 'Vibe Cat',
    imageUrl: null,
    narrativeScore: 58,
    status: 'qualified',
    xPost: {
      tweetId: '1234567895',
      authorUsername: 'nftfrens',
      text: 'why isnt $VIBECAT a thing yet',
      likeCount: 2200,
      repostCount: 410,
      viewCount: 67000,
      canonicalUrl: 'https://x.com/nftfrens/status/1234567895',
    },
    launchCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
];

export const MOCK_PROVIDERS: ProviderInfo[] = [
  {
    id: 'pump',
    name: 'pump.fun',
    description: 'The largest Solana meme coin launchpad. Maximum visibility, instant bonding curve.',
    logoUrl: '/providers/pump.svg',
    websiteUrl: 'https://pump.fun',
    health: {
      providerId: 'pump',
      status: 'healthy',
      latencyMs: 142,
      lastCheckedAt: new Date().toISOString(),
      nextCheckAt: new Date(Date.now() + 60_000).toISOString(),
    },
    capabilities: {
      supportsDevBuy: true,
      supportsFeeShare: false,
      supportsCustomMetadata: true,
      supportsBanner: false,
      supportsWebsite: true,
      supportsTelegram: true,
      supportsTwitterLink: true,
      maxNameLength: 32,
      maxTickerLength: 10,
      maxDescriptionLength: 500,
      maxImageSizeBytes: 5 * 1024 * 1024,
      allowedImageMimeTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
      estimatedLaunchTimeMs: 8_000,
      launchFeeSOL: 0.02,
      featureFlags: { devBuy: true },
    },
    displayOrder: 1,
    isExperimental: false,
  },
  {
    id: 'bags',
    name: 'Bags',
    description: 'Builder-aligned launchpad with on-chain fee share for creators.',
    logoUrl: '/providers/bags.svg',
    websiteUrl: 'https://bags.fm',
    health: {
      providerId: 'bags',
      status: 'healthy',
      latencyMs: 218,
      lastCheckedAt: new Date().toISOString(),
      nextCheckAt: new Date(Date.now() + 60_000).toISOString(),
    },
    capabilities: {
      supportsDevBuy: false,
      supportsFeeShare: true,
      supportsCustomMetadata: true,
      supportsBanner: true,
      supportsWebsite: true,
      supportsTelegram: true,
      supportsTwitterLink: true,
      maxNameLength: 64,
      maxTickerLength: 12,
      maxDescriptionLength: 1000,
      maxImageSizeBytes: 10 * 1024 * 1024,
      allowedImageMimeTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
      estimatedLaunchTimeMs: 10_000,
      launchFeeSOL: 0.03,
      featureFlags: { feeShare: true, banner: true },
    },
    displayOrder: 2,
    isExperimental: false,
  },
];
